local_backend: true

logo_url: /logo.svg

backend:
  name: github
  repo: yacosta738/codary.tech
  branch: main
  base_url: https://sveltia-cms-auth.yunielacosta738.workers.dev/

publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'


media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'src/data/articles'
    create: true
    slug: '{{year}}/{{month}}/{{day}}/{{slug}}'
    fields:
      - name: 'title'
        widget: 'string'
        label: 'Title'
      - name: 'description'
        widget: 'string'
        label: 'Description'
      - name: 'pubDate'
        widget: 'datetime'
        label: 'Publish Date'
      - name: 'lastModified'
        widget: 'datetime'
        label: 'Last Modified'
        required: false
        default: "{{now}}"
      - name: 'author'
        widget: 'relation'
        collection: 'authors'
        value_field: '{{slug}}'
        search_fields: ['name']
        display_fields: ['name']
        multiple: false
      - name: 'cover'
        widget: 'image'
        label: 'Cover'
        default: '/src/assets/images/blog-placeholder-1.avif'
      - name: 'coverAlt'
        widget: 'string'
        label: 'Cover Alt'
      - name: 'tags'
        widget: 'relation'
        collection: 'tags'
        value_field: '{{slug}}'
        search_fields: ['title']
        display_fields: ['title']
        multiple: true
      - name: 'category'
        widget: 'relation'
        collection: 'categories'
        value_field: '{{slug}}'
        search_fields: ['title']
        display_fields: ['title']
        multiple: false
      - name: 'featured'
        widget: 'boolean'
        label: 'Featured'
        default: false
      - name: 'draft'
        widget: 'boolean'
        label: 'Draft'
        default: true
      - name: 'body'
        widget: 'markdown'
        label: 'Body'

  - name: categories
    label: Categories
    label_singular: Category
    folder: src/data/categories
    slug: '{{title}}'
    create: true
    fields:
      - name: title
        widget: string
        label: Title
      - name: order
        widget: number
        label: Order
        required: false
        value_type: int
        min: -1000
        max: 1000
        step: 1

  - name: tags
    label: Tags
    label_singular: Tag
    folder: src/data/tags
    slug: '{{title}}'
    create: true
    fields:
      - name: title
        widget: string
        label: Title

  - name: 'authors'
    label: 'Authors'
    folder: src/data/authors
    slug: '{{name}}'
    create: true
    extension: json
    fields:
      - name: 'name'
        widget: 'string'
        label: 'Name'
      - name: 'email'
        widget: 'string'
        label: 'Email'
      - name: 'avatar'
        widget: 'image'
        label: 'Avatar'

  - name: 'config'
    label: 'Config'
    folder: src/data/config
    slug: 'config'
    create: true
    extension: json
    fields:
      - name: 'brand_name'
        widget: 'string'
        label: 'Brand Name'
      - name: 'title'
        widget: 'string'
        label: 'Title'
      - name: 'description'
        widget: 'string'
        label: 'Site Description'
      - name: 'tag_title'
        widget: 'string'
        label: 'Tag Title'
        default: '{{field.brand_name}} - All tags'
      - name: 'tag_description'
        widget: 'string'
        label: 'Tag Description'
        default: '{{field.brand_name}} - All tags and the count of articles related to each tag'
      - name: 'search_title'
        widget: 'string'
        label: 'Search Title'
        default: '{{field.brand_name}} - Site Search'
      - name: 'search_description'
        widget: 'string'
        label: 'Search Description'
        default: '{{field.brand_name}} - Search articles by title, description, and content'
      - name: 'footer'
        widget: 'object'
        label: 'Footer'
        fields:
          - name: 'links'
            widget: 'list'
            label: 'Links'
            fields:
              - name: 'title'
                widget: 'string'
                label: 'Title'
              - name: 'url'
                widget: 'string'
                label: 'URL'
      - name: 'social'
        widget: 'list'
        label: 'Social'
        fields:
          - name: 'label'
            widget: 'string'
            label: 'Label'
          - name: 'icon'
            widget: 'string'
            label: 'Icon'
          - name: 'url'
            widget: 'string'
            label: 'URL'

  - name: 'page'
    label: 'Pages'
    folder: src/data/dynamic-pages
    create: true
    slug: '{{slug}}'
    fields:
      - name: 'title'
        widget: 'string'
        label: 'Title'
      - name: 'description'
        widget: 'string'
        label: 'Description'
      - name: 'body'
        widget: 'markdown'
        label: 'Body'
